#!/usr/bin/env bash
# feasibility-recheck.sh <series> [--from <kver>] [--to <kver>] [--patched]
#
# Compile-tests a legacy NVIDIA kernel module against a sweep of kernels in
# throwaway containers, WITHOUT a GPU, and reports the first kernel that fails
# (and the failing symbol / error line). This is how we decide kernel_max and
# scope forward-port work.
#
#   --patched   apply the gated patch series first (default: raw upstream module)
#   default sweep: 4.9 .. 7.3 in 0.x steps, using kernel.org mainline headers
#
# Output: a table + writes docs/forward-port-status/<series>.md
set -euo pipefail
. "$(dirname "$0")/lib.sh"
need git

series="${1:?usage: feasibility-recheck.sh <series> [--from X.Y] [--to X.Y] [--patched]}"
shift || true
FROM="4.9"; TO="7.3"; PATCHED=0
while [ $# -gt 0 ]; do case "$1" in
  --from) FROM="$2"; shift;; --to) TO="$2"; shift;; --patched) PATCHED=1;; esac; shift
done

command -v podman >/dev/null && OCI=podman || OCI=docker
ver="$(yq_get ".series.\"$series\".version")"
[ -n "$ver" ] || die "unknown series $series"

# kernel list: minor releases FROM..TO. We use the Debian/Ubuntu 'linux-source'
# or kernel.org tarball headers via a small helper image.
kernels="$(python3 - "$FROM" "$TO" <<'PY'
import sys
def t(v): a=v.split('.'); return (int(a[0]), int(a[1]))
f,to=t(sys.argv[1]),t(sys.argv[2])
maj,mn=f
out=[]
while (maj,mn)<=to:
    out.append(f"{maj}.{mn}")
    mn+=1
    if maj==5 and mn>19: maj,mn=6,0
    if maj==6 and mn>17: maj,mn=7,0     # adjust as new majors land
    if maj==7 and mn>9:  break
print(" ".join(out))
PY
)"

out="$COMMON_ROOT/docs/forward-port-status/$series.md"
mkdir -p "$(dirname "$out")"
{
  echo "# Forward-port status — $series ($ver)"
  echo
  echo "Generated by feasibility-recheck.sh on $(date -u +%F). \`--patched\` = $PATCHED."
  echo
  echo "| kernel | compile | first error |"
  echo "|---|---|---|"
} > "$out"

first_fail=""
for kv in $kernels; do
  log "=== $series vs Linux $kv (patched=$PATCHED) ==="
  res="$("$COMMON_ROOT/scripts/_compile-one.sh" "$series" "$kv" "$PATCHED" 2>&1 || true)"
  status="$(printf '%s' "$res" | tail -1)"
  err="$(printf '%s' "$res" | grep -E 'error:|undefined|no member|implicit declaration' | head -1 | cut -c1-120 | tr '|' '/')"
  case "$status" in
    OK) echo "| $kv | ✅ | |" >> "$out"; log "  OK" ;;
    SKIP) echo "| $kv | ⚠️ skip (no headers) | |" >> "$out" ;;
    *)  echo "| $kv | ❌ | \`$err\` |" >> "$out"
        [ -z "$first_fail" ] && first_fail="$kv"
        warn "  FAIL: $err" ;;
  esac
done

{
  echo
  if [ -n "$first_fail" ]; then
    echo "**First failing kernel: $first_fail.**  Suggested \`kernel_max\` = the last ✅ above."
    echo "Next: \`forward-port.sh $series $first_fail\` to scaffold the patch."
  else
    echo "**All kernels in [$FROM, $TO] compile.**  \`kernel_max\` can be raised to $TO."
  fi
} >> "$out"
log "wrote $out"
cat "$out"
